#!/bin/bash
# =============================================================================
# Install/Update Content-Security-Policy header in Nginx config — MET NONCES
# =============================================================================
# Strategie:
#   1. Per-request nonce wordt afgeleid van $request_id (Nginx core var).
#      We voegen 'rv-' prefix toe via map → variabele $csp_nonce.
#   2. sub_filter vervangt __CSP_NONCE__ in de geserveerde index.html door
#      die nonce, zodat <script nonce="..."> matcht met de header.
#   3. CSP-snippet zet script-src 'nonce-$csp_nonce' 'strict-dynamic'
#      (geen 'unsafe-inline' meer voor scripts!). 'strict-dynamic' zorgt dat
#      door nonced scripts geladen chunks ook vertrouwd worden — Vite-vriendelijk.
#   4. style-src behoudt 'unsafe-inline' — Tailwind/Vite injecteren runtime
#      stijlen die niet praktisch met nonces te bedienen zijn.
#
# Vereist Nginx module ngx_http_sub_module (standaard aanwezig in Ubuntu).
#
# Idempotent: safe to run multiple times. Backs up before each change.
#
# Usage:  sudo bash scripts/install-csp.sh [/pad/naar/nginx-config]
# =============================================================================

set -euo pipefail

NGINX_CONF="${1:-}"
if [[ -z "$NGINX_CONF" ]]; then
  for candidate in \
    /etc/nginx/sites-available/rv-installatie \
    /etc/nginx/sites-available/rv-installatie.nl \
    /etc/nginx/sites-available/comfort-connect \
    /etc/nginx/sites-available/default; do
    if [[ -f "$candidate" ]]; then
      NGINX_CONF="$candidate"
      break
    fi
  done
fi
if [[ -z "$NGINX_CONF" || ! -f "$NGINX_CONF" ]]; then
  FOUND=$(grep -rlE 'server_name[[:space:]]+[^;]*rv-installatie\.nl' /etc/nginx/sites-available/ 2>/dev/null | head -1 || true)
  [[ -n "$FOUND" ]] && NGINX_CONF="$FOUND"
fi

SNIPPET_FILE="/etc/nginx/snippets/csp-rv.conf"
NONCE_MAP_FILE="/etc/nginx/conf.d/csp-nonce-map.conf"
BACKUP_DIR="/etc/nginx/backups"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/$(basename "${NGINX_CONF:-unknown}").${TIMESTAMP}.bak"

INCLUDE_LINE="    include snippets/csp-rv.conf;  # === MANAGED CSP (install-csp.sh) ==="
SUBFILTER_LINE="    sub_filter '__CSP_NONCE__' \$csp_nonce;  # === MANAGED CSP (install-csp.sh) ==="
SUBFILTER_ONCE="    sub_filter_once off;  # === MANAGED CSP (install-csp.sh) ==="
MARKER="MANAGED CSP (install-csp.sh)"

# Note: \$csp_nonce wordt door Nginx geëvalueerd, NIET door bash.
CSP_VALUE="default-src 'self'; \
script-src 'self' 'nonce-\$csp_nonce' 'strict-dynamic' https:; \
script-src-elem 'self' 'nonce-\$csp_nonce' 'strict-dynamic' https:; \
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
font-src 'self' data: https://fonts.gstatic.com; \
img-src 'self' data: blob: https:; \
connect-src 'self' https://*.sentry.io https://*.ingest.sentry.io https://*.ingest.de.sentry.io https://static.cloudflareinsights.com https://nominatim.openstreetmap.org https://*.tile.openstreetmap.org; \
frame-src 'self' https://www.google.com; \
worker-src 'self' blob:; \
media-src 'self' blob: data:; \
object-src 'none'; \
base-uri 'self'; \
form-action 'self'; \
frame-ancestors 'none'; \
upgrade-insecure-requests"

[[ $EUID -ne 0 ]] && { echo "❌ Run als root: sudo bash $0"; exit 1; }

if [[ -z "$NGINX_CONF" || ! -f "$NGINX_CONF" ]]; then
  echo "❌ Nginx config niet gevonden."
  ls -1 /etc/nginx/sites-available/ 2>/dev/null | sed 's/^/     /'
  exit 1
fi

echo "📄 Config: $NGINX_CONF"

mkdir -p "$BACKUP_DIR" /etc/nginx/snippets /etc/nginx/conf.d
cp "$NGINX_CONF" "$BACKUP_FILE"
echo "📦 Backup: $BACKUP_FILE"

# -----------------------------------------------------------------------------
# 1. Globale nonce-map (in conf.d, dus in http{} scope)
# -----------------------------------------------------------------------------
cat > "$NONCE_MAP_FILE" <<'EOF'
# Auto-generated by install-csp.sh — per-request CSP nonce
# Gebruikt Nginx's $request_id (16 hex bytes, uniek per request) als nonce.
map $request_id $csp_nonce {
    default $request_id;
}
EOF
echo "📝 Nonce map: $NONCE_MAP_FILE"

# -----------------------------------------------------------------------------
# 2. CSP snippet
# -----------------------------------------------------------------------------
cat > "$SNIPPET_FILE" <<EOF
# Auto-generated by install-csp.sh on ${TIMESTAMP}
add_header Content-Security-Policy "${CSP_VALUE}" always;
EOF
echo "📝 Snippet: $SNIPPET_FILE"

# -----------------------------------------------------------------------------
# 3. Verwijder oude includes (idempotent)
# -----------------------------------------------------------------------------
sed -i "/${MARKER}/d" "$NGINX_CONF"
sed -i '/# === MANAGED CSP HEADER (install-csp.sh) ===/,/# === END MANAGED CSP HEADER ===/d' "$NGINX_CONF"

if grep -qiE 'add_header[[:space:]]+Content-Security-Policy' "$NGINX_CONF"; then
  echo "⚠️  Handmatige Content-Security-Policy gevonden in config:"
  grep -n -iE 'add_header[[:space:]]+Content-Security-Policy' "$NGINX_CONF"
  echo "    Verwijder die handmatig en run dit script opnieuw."
  exit 1
fi

# -----------------------------------------------------------------------------
# 4. Voeg toe:
#    - na elke 'server {'   → CSP include + sub_filter setup
#    - na elke 'location {' → CSP include + sub_filter regels (non-inherit fix)
# -----------------------------------------------------------------------------
awk -v inc="$INCLUDE_LINE" -v sf="$SUBFILTER_LINE" -v sfo="$SUBFILTER_ONCE" -v sft="$SUBFILTER_TYPES" '
  /^[[:space:]]*server[[:space:]]*\{/ {
    print
    print inc
    print sf
    print sfo
    print sft
    next
  }
  /^[[:space:]]*location[[:space:]].*\{[[:space:]]*$/ {
    print
    print inc
    print sf
    print sfo
    print sft
    next
  }
  { print }
' "$NGINX_CONF" > "${NGINX_CONF}.tmp"

mv "${NGINX_CONF}.tmp" "$NGINX_CONF"

INSERTED=$(grep -c "$MARKER" "$NGINX_CONF" || true)
echo "✅ CSP+nonce include toegevoegd op ${INSERTED} plaats(en)."

# -----------------------------------------------------------------------------
# 5. Test & reload
# -----------------------------------------------------------------------------
echo ""
echo "🔍 Nginx config testen..."
if nginx -t 2>&1; then
  echo ""
  echo "♻️  Nginx herladen..."
  systemctl reload nginx
  echo ""
  echo "✅ KLAAR! Verifieer:"
  echo "  curl -sI https://rv-installatie.nl | grep -i content-security"
  echo "  curl -s  https://rv-installatie.nl | grep -o 'nonce=\"[^\"]*\"' | head"
  echo ""
  echo "Beide nonces moeten matchen. Cloudflare ~30s cache, dan:"
  echo "  https://securityheaders.com/?q=https://rv-installatie.nl&followRedirects=on&hide=on"
else
  echo ""
  echo "❌ Nginx test FAILED — terugrollen..."
  cp "$BACKUP_FILE" "$NGINX_CONF"
  rm -f "$NONCE_MAP_FILE"
  echo "✅ Backup teruggezet."
  exit 1
fi
