#!/bin/bash
# =============================================================================
# Install/Update Content-Security-Policy header in Nginx config
# =============================================================================
# Strategie: schrijf CSP in een SNIPPET (/etc/nginx/snippets/csp-rv.conf) en
# include die snippet in elk relevant 'location' block + op server niveau.
#
# Achtergrond: Nginx's add_header is NIET inheriting — zodra een location
# block ÉÉN eigen add_header heeft, vervallen ALLE parent headers in dat
# block. Daarom plaatsen we de include in elk location block dat we vinden.
#
# Idempotent: safe to run multiple times. Backs up before each change.
#
# Usage:  sudo bash scripts/install-csp.sh [/pad/naar/nginx-config]
# =============================================================================

set -euo pipefail

# Auto-detect Nginx config
NGINX_CONF="${1:-}"
if [[ -z "$NGINX_CONF" ]]; then
  for candidate in \
    /etc/nginx/sites-available/rv-installatie \
    /etc/nginx/sites-available/rv-installatie.nl \
    /etc/nginx/sites-available/comfort-connect \
    /etc/nginx/sites-available/default; do
    if [[ -f "$candidate" ]]; then
      NGINX_CONF="$candidate"
      break
    fi
  done
fi
if [[ -z "$NGINX_CONF" || ! -f "$NGINX_CONF" ]]; then
  FOUND=$(grep -rlE 'server_name[[:space:]]+[^;]*rv-installatie\.nl' /etc/nginx/sites-available/ 2>/dev/null | head -1 || true)
  [[ -n "$FOUND" ]] && NGINX_CONF="$FOUND"
fi

SNIPPET_FILE="/etc/nginx/snippets/csp-rv.conf"
BACKUP_DIR="/etc/nginx/backups"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/$(basename "${NGINX_CONF:-unknown}").${TIMESTAMP}.bak"

INCLUDE_LINE="    include snippets/csp-rv.conf;  # === MANAGED CSP (install-csp.sh) ==="
MARKER="MANAGED CSP (install-csp.sh)"

CSP_VALUE="default-src 'self'; \
script-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.cloudflareinsights.com https://*.sentry.io https://browser.sentry-cdn.com https://js.sentry-cdn.com https://pagead2.googlesyndication.com https://*.googlesyndication.com https://www.google.com https://www.gstatic.com https://fundingchoicesmessages.google.com; \
script-src-elem 'self' 'unsafe-inline' https://static.cloudflareinsights.com https://*.sentry.io https://browser.sentry-cdn.com https://js.sentry-cdn.com https://pagead2.googlesyndication.com https://*.googlesyndication.com https://www.google.com https://www.gstatic.com https://fundingchoicesmessages.google.com; \
style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; \
font-src 'self' data: https://fonts.gstatic.com; \
img-src 'self' data: blob: https:; \
connect-src 'self' https://*.sentry.io https://*.ingest.sentry.io https://*.ingest.de.sentry.io https://static.cloudflareinsights.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://fundingchoicesmessages.google.com; \
frame-src 'self' https://www.google.com https://googleads.g.doubleclick.net https://*.googlesyndication.com https://fundingchoicesmessages.google.com; \
worker-src 'self' blob:; \
media-src 'self' blob: data:; \
object-src 'none'; \
base-uri 'self'; \
form-action 'self'; \
frame-ancestors 'none'; \
upgrade-insecure-requests"

# -----------------------------------------------------------------------------
# Pre-flight
# -----------------------------------------------------------------------------
[[ $EUID -ne 0 ]] && { echo "❌ Run als root: sudo bash $0"; exit 1; }

if [[ -z "$NGINX_CONF" || ! -f "$NGINX_CONF" ]]; then
  echo "❌ Nginx config niet gevonden."
  echo "   Beschikbaar in /etc/nginx/sites-available/:"
  ls -1 /etc/nginx/sites-available/ 2>/dev/null | sed 's/^/     /'
  echo ""
  echo "   Geef pad expliciet mee: sudo bash $0 /etc/nginx/sites-available/JOUW-CONFIG"
  exit 1
fi

echo "📄 Config: $NGINX_CONF"

mkdir -p "$BACKUP_DIR" /etc/nginx/snippets
cp "$NGINX_CONF" "$BACKUP_FILE"
echo "📦 Backup: $BACKUP_FILE"

# -----------------------------------------------------------------------------
# Schrijf de snippet (single source of truth voor de CSP value)
# -----------------------------------------------------------------------------
cat > "$SNIPPET_FILE" <<EOF
# Auto-generated by install-csp.sh on ${TIMESTAMP}
# Do not edit manually — re-run scripts/install-csp.sh to update.
add_header Content-Security-Policy "${CSP_VALUE}" always;
EOF
echo "📝 Snippet geschreven: $SNIPPET_FILE"

# -----------------------------------------------------------------------------
# Verwijder oude includes (idempotent)
# -----------------------------------------------------------------------------
sed -i "/${MARKER}/d" "$NGINX_CONF"

# Verwijder ook eventuele oude add_header Content-Security-Policy regels
# die door een vorige versie van dit script zijn toegevoegd
sed -i '/# === MANAGED CSP HEADER (install-csp.sh) ===/,/# === END MANAGED CSP HEADER ===/d' "$NGINX_CONF"

# Waarschuw voor handmatige CSP elders
if grep -qiE 'add_header[[:space:]]+Content-Security-Policy' "$NGINX_CONF"; then
  echo "⚠️  Handmatige Content-Security-Policy gevonden in config:"
  grep -n -iE 'add_header[[:space:]]+Content-Security-Policy' "$NGINX_CONF"
  echo "    Verwijder die handmatig en run dit script opnieuw."
  exit 1
fi

# -----------------------------------------------------------------------------
# Voeg include toe:
#   1. Direct na elke 'server {' regel (voor server-level fallback)
#   2. Direct na elke 'location ... {' regel (overschrijft Nginx's non-inherit)
# -----------------------------------------------------------------------------
awk -v inc="$INCLUDE_LINE" '
  # server { block — alleen voor HTTPS server (port 443 / ssl)
  /^[[:space:]]*server[[:space:]]*\{/ {
    print
    print inc
    next
  }
  # location ... { block — voeg include toe na opening
  /^[[:space:]]*location[[:space:]].*\{[[:space:]]*$/ {
    print
    print inc
    next
  }
  { print }
' "$NGINX_CONF" > "${NGINX_CONF}.tmp"

mv "${NGINX_CONF}.tmp" "$NGINX_CONF"

INSERTED=$(grep -c "$MARKER" "$NGINX_CONF" || true)
echo "✅ CSP include toegevoegd op ${INSERTED} plaats(en)."

# -----------------------------------------------------------------------------
# Test & reload
# -----------------------------------------------------------------------------
echo ""
echo "🔍 Nginx config testen..."
if nginx -t 2>&1; then
  echo ""
  echo "♻️  Nginx herladen..."
  systemctl reload nginx
  echo ""
  echo "✅ KLAAR! Verifieer met:"
  echo "  curl -sI https://rv-installatie.nl | grep -i content-security"
  echo ""
  echo "Geef Cloudflare ~30s om de cache te verversen, dan:"
  echo "  https://securityheaders.com/?q=https://rv-installatie.nl&followRedirects=on&hide=on"
else
  echo ""
  echo "❌ Nginx test FAILED — terugrollen..."
  cp "$BACKUP_FILE" "$NGINX_CONF"
  echo "✅ Backup teruggezet. Nginx NIET herladen."
  exit 1
fi
